### PR TITLE
add razorSupport2 feature branch for .net core razor support step 2

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
can you take a look?

**Comment by heejaechang** [comment]
@JoeRobich  will this automatically create feature branch for us or do I need to manually go and create one?

**Comment by JoeRobich** [comment]
@heejaechang I think you will need to create the branch. If you don't need daily merges, you can also specify a "weekly" frequency.

**Comment by heejaechang** [comment]
@JoeRobich I will go weekly if daily is too much later.

**Pull request merged**
