### PR TITLE
Build components list from vs manifests in artifacts

### PR DESCRIPTION
**Pull request by JoeRobich**
Resolves https://github.com/dotnet/roslyn-tools/issues/979

@RikkiGibson

### CODE REVIEW

**Comment by LittleLittleCloud** [comment]
Hi @JoeRobich @RikkiGibson is there an estimation of when this PR get merged in.

Regards

**Review by RikkiGibson — APPROVED** [review]
The change LGTM but would like to see an insertion which uses this change if possible.

**Comment by JoeRobich** [comment]
> would like to see an insertion which uses this change if possible.

Lemme get one generated

**Comment by JoeRobich** [comment]
@RikkiGibson Here is a test insertion - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/331195?discussionId=3448374&_a=files

**Pull request merged**
