### PR TITLE
Fixing PR creation for ADO branches

### PR DESCRIPTION
**Pull request by AbhitejJohn**
Fixing the merging of changes across branches in VSTS. I'd eventually like this to re-use the github auto merge workflow for all its goodness. 
Also updated the branch matrix.

### CODE REVIEW

**Comment by AbhitejJohn** [comment]
@jasonmalinowski : How do I update the azure functions package with this change for validation? I see [this](https://github.com/dotnet/roslyn-tools/blob/master/src/AzureFunctionPackage/CreateZipPackage.ps1) but I'm not sure what uploads the package created.

**Comment by jasonmalinowski** [comment]
@brettfo you know the details?

**Comment by brettfo** [comment]
Each merge into `master` triggers a new build and each build of `master` auto-deploys the functions: https://github.com/dotnet/roslyn-tools/blob/b33986e32e543329c57c3c09c98012c43ff7617e/.vsts-ci.yml#L110

**Comment by AbhitejJohn** [comment]
@brettfo : Excellent, thanks.

**Pull request merged**
