### PR TITLE
Updating SignTool to not require a strong name for assemblies.

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
@jaredpar for review.

Also, I was thinking that when you get the new signing validation up and working, we should have it run on `test`, for any assembly where `strongName` is `null`, since they should be getting signed with a full key there as well. Thoughts?

**Comment by tannergooding** [comment]
FYI. @tmat on the version bump in repo-toolset.

The version will be correct, provided this is merged today and is included in the next signed build.

**Comment by tmat** [comment]
If we want a change to be available we first need to make that change, kick off microbuild and then update the toolset to the nuget version that comes out of the build.

**Comment by tmat** [comment]
👍

**Comment by tannergooding** [comment]
ping @jaredpar, this is currently blocking.

**Pull request merged**
