### PR TITLE
Update dotnet/sdk merges with 2.1.5xx

### PR DESCRIPTION
**Pull request by nguerrera**
Extra merge bot hop for introduction of 2.1.5xx in dotnet/sdk in between 2.1.4xx and 2.2.1xx.

cc @livarcocc @peterhuene

### CODE REVIEW

**Comment by livarcocc** [comment]
I had this on my TODO list, now I don't.

**Comment by brettfo** [comment]
@dotnet-bot test prtest/Windows/NT/Debug please

**Comment by brettfo** [comment]
@dotnet-bot test prtest/Ubuntu16.04/Debug please

**Comment by nguerrera** [comment]
@dotnet-bot Test prtest/Windows/NT/Debug

**Comment by nguerrera** [comment]
@brettfo Can we merge this?

**Comment by nguerrera** [comment]
Thanks.

**Pull request merged**
