### PR TITLE
adding DownloadRoslynVsixes

### PR DESCRIPTION
**Pull request by jmarolf**
@tmat for review.  Adding a tool used for getting vsixes for integration test runs.

### CODE REVIEW

**Comment by jmarolf** [comment]
Merging preemptively.  Let me know if there is anything you need me to fixup

**Comment by jaredpar** [comment]
Which repo is going to be using this tool?  Is it for project-system or LUT?

**Comment by jmarolf** [comment]
Project system in the changes I am making.  I plan for LUT to take advantage of it as well.  Its not sensible to have fixed versions of roslyn we are testing against, we should at least be validating integration with the nightlies

**Comment by jaredpar** [comment]
Gotcha

**Pull request merged**
