### PR TITLE
Add a `-diag` switch to sign tool to show more verbose output

### PR DESCRIPTION
**Pull request by natemcmaster**
Make it easier to gather more detailed information when something is going wrong.

### CODE REVIEW

**Comment by natemcmaster** [comment]
My editor did what it was told to do.
https://github.com/dotnet/roslyn-tools/blob/3153452c268f47a8282309d6ecb759b0c7697d2c/.editorconfig#L18-L24

**Comment by jmarolf** [comment]
@natemcmaster binary logging should already work for signtool, that's about as diagnostic as you can get. What is the binlog capturing?

**Comment by natemcmaster** [comment]
I tried that, but the problem was that that msbuild invocation never terminated, so the binary log was corrupt and couldn't be read. I had to re-create the generated "build.proj" file and invoke MSBuild manually with `/v:diag` to figure out what was happening.

**Comment by natemcmaster** [comment]
Thanks for the review @jmarolf. I don't have write permissions, so someone else will have to merge this for me.

**Pull request merged**
