### PR TITLE
Updating PipeBuild.Publish to pass along manifest information.

### PR DESCRIPTION
**Pull request by tannergooding**
Just a first pass doing nearly the simplest thing.

### CODE REVIEW

**Comment by tmat** [comment]
Why don't we just use the environment variables? The publishing is only relevant in official builds where the variables are always available.

**Comment by tannergooding** [comment]
> Why don't we just use the environment variables? T

We don't use them directly in order to more easily support other environments or future directions where we don't use a build system that has those variablese.

**Comment by tmat** [comment]
I'd add those when that will happen. Adding them now makes things unnecessarily complex.

**Comment by tannergooding** [comment]
Updated.

**Comment by tmat** [comment]
Thanks!

**Comment by dagood** [comment]
I think this is missing a Feed package upgrade:

https://devdiv.visualstudio.com/DevDiv/_build?buildId=1301675

> error MSB4064: The "ManifestName" parameter is not supported by the "PushToBlobFeed" task.

**Comment by tannergooding** [comment]
@dagood, It is currently targeting `2.1.0-prerelease-02221-02` (https://github.com/dotnet/roslyn-tools/blob/1658d012a482a0caaff7a58a0dc941bb417edcd3/sdks/RepoToolset/tools/DefaultVersions.props#L41).

What is the correct version to target?

**Pull request merged**
