### PR TITLE
RIT: Skip builds tagged with 'DoesNotRequireInsertion'

### PR DESCRIPTION
**Pull request by dpoeschl**

### CODE REVIEW

**Comment by dpoeschl** [comment]
Do we need to have this be per-target-branch instead of just flagging the build across the board.

**Comment by dpoeschl** [comment]
Tagging @jasonmalinowski since we talked about this earlier today.

**Comment by jasonmalinowski** [comment]
@dpoeschl It is technically a per-target-branch concept, yes. I could imagine us wanting a per-branch flag because we might say something like "we don't need to insert this build before the division snaps branches, but once it does we want to insert it somewhere else."

**Comment by jasonmalinowski** [comment]
Given the ease of including the branch name into the tag....I'd just go with that.

**Comment by dpoeschl** [comment]
Okay, will do.

**Comment by dpoeschl** [comment]
Okay, it's now per-branch.

**Comment by dpoeschl** [comment]
Gonna give it a spin.

**Pull request merged**
